### ISSUE TITLE
Java server not working

### ISSUE THREAD

**Issue by mobaraksaid** [TeamSQL/desktop-app#372]
I'm running the newest stable 4.0. 341 on MAC high sierra.
When i try to connect to my MySQL DB i get the error **Java server not working**.

**Comment by murteza** [comment]
Hi @mobaraksaid ,

Let me check with the team and get back to you.

--
Erol from TeamSQL

**Comment by murteza** [comment]
Hi @mobaraksaid ,

We’ll fix this issue with the next update. 
So, please stay tuned!

--
Erol from TeamSQL

**Comment by fatihdervisi** [comment]
Hi @mobaraksaid,

Can you please check our database drivers is installed correctly in this path : 
`/Users/{"your-user-here"}/Library/Application\ Support/TeamSQL/AppCache/jdbc-drivers` .

And can you try to connect to the database again with TeamSQL and after you've got the error,  try to list your java processes in your terminal using this command : `ps aux | grep "TEAMSQL_DRIVER_MODULE"` 

Thanks.

**Comment by mobaraksaid** [comment]
When is the next release? I can't use the application because of this error and i don't want to start over with another application.

**Comment by init-0** [comment]
I am seeing this issue across MySQL, Postgres and Redshift connections.  Would love to use this app but without the basic connection...

**Comment by jcusick13** [comment]
Hi @mobaraksaid,

I'm running into the same issue -- I'm trying to add a connection to a MSSQL DB and when I click `Test Connection` I get the same "Java server not working" error message as the user above. I'm using macOS High Sierra v10.13.6. 

I followed your suggestions above and found the following in `../TeamSQL/AppCache/jdbc-drivers`
* `ts-mssql-extenstion-0.0.1-SNAPSHOT.jar`
* `ts-mysql-extenstion-0.0.1-SNAPSHOT.jar`
* `ts-oracle-extenstion-0.0.1-SNAPSHOT.jar`
* `ts-postgresql-extenstion-0.0.1-SNAPSHOT.jar`
* `ts-redshift-extenstion-0.0.1-SNAPSHOT.jar`

After receiving the error and typing `$ ps aux | grep "TEAMSQL_DRIVER_MODULE"`, I saw the `ts-mssql-extension-0.0.1-SNAPSHOT.jar` listed on two different ports. Both instances had the flag `-Dmodule_name=TEAMSQL_DRIVER_MODULE`.

Do you have any suggestions for other things to check or suggested workarounds to connect to the db? Or if this is already covered in the next release, do you know when that is planned for?

Thanks!

**Comment by selcukayhan** [comment]
Hi @mobaraksaid , @jcusick13 , @init-0  ,

May I have Java and TeamSQL versions of your environment. 
(You can type " java -version " to terminal)

Thank you.

**Comment by jcusick13** [comment]
Hi @selcukayhan,

My Java version is:
```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
and my TeamSQL is `Version 4.0.357 (4.0.357.357)`

**Comment by selcukayhan** [comment]
Hi @jcusick13 ,

We are checking it now. 

Thanks.

**Comment by igor-finery** [comment]
I have the same issue on MacOS 10.13.6

java version "1.8.0_121"

Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)


and my TeamSQL is Version 4.0.357 (4.0.357.357)

**Comment by selcukayhan** [comment]
Hi There, 

We fixed this issue and published it on today's release which versioned as **4.0.371** 

Thank you for your understanding.

**Comment by igor-finery** [comment]
Thanks, it works now.

**Comment by jcusick13** [comment]
@selcukayhan, it works for me as well. Thank you for the effort! 👍

**Comment by alexalouit** [comment]
Same error for me with 4.0.371 version

**Comment by AlbertoMontalesi** [comment]
still getting error

TeamSQL version 4.0.371

$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

Ubuntu 18.04

**Comment by lemil** [comment]
Hi Guys!, found the issue. Apparently there's a missing backslash in the path that the java server uses ( .../Application Support/..). Try launching the service by hand fixing the path.

This is how it works fine (at least for me)....

/usr/bin/java -jar /Users/{your-user-name-here}/Library/Application\ Support/TeamSQL/AppCache/jdbc-drivers/ts-mysql-extension-0.0.1-SNAPSHOT.jar --server.port=63192 -Dmodule_name=TEAMSQL_DRIVER_MODULE

**Comment by quequegerones** [comment]
I'm having the same error... I've just downloaded the app, trying to connect for the first time

**Comment by wayneandrews** [comment]
I'm having the same issue on Ubuntu 14.04

**Comment by murteza** [comment]
Hi @michcald @wayneandrews @quequegerones @AlbertoMontalesi @alexalouit ,

We released a new version yesterday. Did you update on TeamSQL 4.0.371?

**Comment by michcald** [comment]
@murteza 

The app started to work again now. I confirm I am using version 4.0.371 but unfortunately I cannot tell if I was having the issue with this same version or not (I forgot to check).

Anyways, the issue no longer persist for me, so thanks

**Comment by wayneandrews** [comment]
I still have the same error after running the latest version.

**Comment by isfo** [comment]
same error here.
java version: 10.0.2
teamsql version: 4.0.376.376

**Comment by michcald** [comment]
Continuation of my last comment https://github.com/TeamSQL/desktop-app/issues/372#issuecomment-424745727

This morning I opened again the app (no updates still with version 4.0.371) and I am having again the same message "Java server not working"

**Comment by murteza** [comment]
Hi @michcald , @alexalouit , @isfo , @wayneandrews 

We'll fix this issue today and release a hotfix for that.
So, please stay tuned!

**Comment by alexalouit** [comment]
Same error with 4.0.379 version

**Comment by michcald** [comment]
It's working for me too. Thanks

**Comment by murteza** [comment]
Hi @alexalouit ,

We are investigating your case. So, please stay tuned!

**Comment by alexalouit** [comment]
@murteza there's is anything else I can do, like generate a debug file?

**Comment by zanvd** [comment]
Hi, for me version 4.0.379 is working on Linux Mint 18.3.

Thank you,
Žan

**Comment by alex-lit** [comment]
Same error on Linux Deepin 15.7

![deepinscreenshot_ - _20181004114449](https://user-images.githubusercontent.com/5243967/46462749-ea1eac00-c7ca-11e8-94b6-eb5060962d19.png)

**Comment by alex-lit** [comment]
@selcukayhan Thanks, it works.

**Comment by SadioD** [comment]
Hi @selcukayhan,
I've just installed the latest version (4.0.379) and then failed to create a new connection (MySQL) on localhost with the same error message "java server not working"

Java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by murteza** [comment]
Hİ @SadioD 

What is your MySQL version?

**Comment by marvi182** [comment]
Hello there!
I have the same issue when i'm trying to connect via Windows Auth to SQL Server.
My java version 1.8.0_181
Ubuntu 18.04
TeamSQL 4.0.379

i'm getting the same error about java server not working

Thanks for your help!!!!
