### ISSUE TITLE
Java SSL error with postgresql

### ISSUE THREAD

**Issue by SkipMike** [TeamSQL/desktop-app#381]
I'm on 4.0.341 on ubuntu 18.04. When I try to connect to a production Google CloudSQL, I get 
![screenshot-20180905-10 39 59](https://user-images.githubusercontent.com/26072688/45107892-4a50fe00-b0f8-11e8-9179-6af7e442a77c.png) this error. I can connect to my local stuff just fine. I think I also got some server error from TeamSQL last night.

**Comment by murteza** [comment]
Hi @SkipMike ,

Thank you for reaching out to us. Let me check with the team and get back to you

**Comment by cbailly42** [comment]
I have the exact same error on MacOS 10.13.6 since i have installed the version 4.0.341 of TeamSQL. Everything was working fine previously. 

I try to connect to a Heroku Postgres database. 

The same database setup work with the previous version of teamSQL that i have on another Mac with the same version of MacOS (which proves that the problem comes from the latest version of teamsql). 

Hope you will find a solution soon, do not hesitate if you need more information to locate the bug 😃

**Comment by SkipMike** [comment]
I've updated to 4.0.357 with the same error still happening.

**Comment by barisozanguler** [comment]
Hi @SkipMike @cbailly42 

We are still investigating this bug. It's looks like happen in some service providers which cause of root certificates and JDBC's keystore as we think. We will keep you updated for progress.

Thanks.

**Comment by murteza** [comment]
Hi @SkipMike @cbailly42 ,

We released a new version yesterday. Can you update and try again, please?

**Comment by lastgleam** [comment]
Hi @murteza 

![image](https://user-images.githubusercontent.com/18328030/46118801-52a5e000-c243-11e8-81f5-bc60278475e8.png)
I still get the same error on version 4.0.376. (desktop OS is macOS 10.14 Mojave)
I tried to connect to Google CloudSQL too.
with [pgAdmin4](https://www.pgadmin.org/), It has been connected with no errors.

I wish I could connect to Google CloudSQL via TeamSQL.

**Comment by cbailly42** [comment]
Hi @murteza,
Sadly it still doesn't work on v4.0.376 on MacOS 10.13.6 to connect to a Heroku Postgres Database ...

![image](https://user-images.githubusercontent.com/8553492/46131561-423e3700-c23c-11e8-9afe-223d054116ee.png)

I hope you will find and resolve the bug so that i can use TeamSQL again ! 😄

**Comment by murteza** [comment]
Hi @lastgleam 

You can connect Google Cloud PG via SSL after converting your private key file to .pk8 format with command as below ;

openssl pkcs8 -topk8 -inform PEM -outform DER -in client-key.pem -out client-key.pk8 -nocrypt

**Comment by urossmolnik** [comment]
I am still getting this error with new build: `Version 4.0.379 (4.0.379.379)`

**Comment by george** [comment]
I got it working by enabling SSL in the connection config. Then, in the SSL options section that becomes visible, select Yes for Reject Unauthorized. HTH
