### ISSUE TITLE
Popup database listing not working with PostgreSQL & Redshift

### ISSUE THREAD

**Issue by erenbaydemir** [TeamSQL/desktop-app#72]
When opening a new tab with server selection (CMD + SHIFT + N) or opening a query shared by someone with a PostgreSQL / Redshift connection, UI is stuck with the 'Retreiving database list' message. 

![2017-04-06_08h21_21](https://cloud.githubusercontent.com/assets/688276/24746176/d2e3cf6a-1ac0-11e7-96bf-75756f6caf18.png)

**Comment by erenbaydemir** [comment]
Fixed, will be included in the next update

**Comment by GaboP87** [comment]
Hi,

I am using TeamSQL for Mac and I am still having the above mentioned issue
<img width="905" alt="screen shot 2018-03-12 at 23 07 03" src="https://user-images.githubusercontent.com/32514548/37312184-5465d73c-264a-11e8-83a7-b4490a7ba467.png">

Can you please tell me why I am having this problem? PostgreSQL connection.
I get connected to the DB but the list of Databases Retrieve hangs indefinitely.

Thanks,
Gabriel
